Coupon crud
umaimaz123/ECommerce-EMS pull request #11
Opened 2022-02-01 12:51 UTC by umaimaz123

2022-02-01 19:43 UTC, Sohair63 requested changes

2022-02-01 19:43 UTC, Sohair63 commented on app/controllers/admin/coupons_controller.rb
> +      @coupons = @q.result(distinct: true) if params[:excel]
this does not seems correct.

2022-02-01 19:43 UTC, Sohair63 commented on app/controllers/admin/coupons_controller.rb
> +      end
1. we should not add business logic e.g loops and computation in the controller.
2. we should not create/update/find/where in loop.

2022-02-01 19:43 UTC, Sohair63 commented on app/controllers/admin/coupons_controller.rb
> +        render 'new'
decide one for similarity, either you want to use string notation or symbol?

2022-02-01 19:43 UTC, Sohair63 commented on app/controllers/admin/products_controller.rb
> +      params.require(:product).permit(:title, :price, :description, :state, :image, :category_id, :coupon_id)
why we are passing ids in the request data?

Can you see if we can avoid this, as this is security leaks and anyone can manage to use sequential ID to break this code.

2022-02-01 19:43 UTC, Sohair63 commented on app/models/coupon.rb
> +    where('lower(name) LIKE :term OR cast(value as text) LIKE :term', term: "%#{param}%")
```suggestion
    where('lower(name) LIKE :term OR cast(value as text) LIKE :term', term: "%#{term.to_s.downcase}%")
```

2022-02-01 19:43 UTC, Sohair63 commented on app/views/admin/coupons/_form.html.erb
> +       <%= select_tag 'products[]', options_from_collection_for_select(Product.all, "id", "title"), multiple: true, required: true, class:"form-control js-products" %>
if you have 100000 products, this simple form will slow down the application to just load this dropdown.

Try to use select2 in a better way here, i.e. search will return the matching data from server side

2022-02-01 19:43 UTC, Sohair63 commented on app/views/admin/coupons/_form.html.erb
> +})
we avoid writing scripts in htm files.

2022-02-01 19:43 UTC, Sohair63 commented on app/views/admin/coupons/index.html.erb
> +<%= will_paginate @couponsies %>
spelling?

2022-02-01 19:43 UTC, Sohair63 commented on app/views/admin/dashboard/index.html.erb
> +  <%= link_to 'Coupos', admin_coupons_path, class:"btn btn-dark" %>
spelling?

2022-02-01 19:43 UTC, Sohair63 commented on db/migrate/20220125093838_create_coupon.rb
> +      t.integer :value
can coupons exist without these? 

1. add table level validations in all table, at least for demo project, this will improve learning.
2. value can be alphanumeric and unique.

2022-02-01 19:43 UTC, Sohair63 commented on package.json
> +    "select2": "^4.1.0-rc.0",
just a note, if we update jquery everytime with a new lib, this can lead to bugs for old packages.

2022-02-01 19:44 UTC, Sohair63 commented
@umaimaz123 do run rubocop once, I saw a lot of lints in this PR, that rubocop will help to resolve.

2022-02-09 13:46 UTC, Sohair63 requested changes

2022-02-09 13:46 UTC, Sohair63 commented on app/javascript/custom/select2.js
> +        }
We should replace rather than append.

2022-02-09 13:46 UTC, Sohair63 commented on app/javascript/custom/select2.js
> +            return { term: params.term };
lint

2022-02-09 13:46 UTC, Sohair63 commented on app/javascript/custom/select2.js
> +        delay: 250,
why delay?

2022-02-09 14:39 UTC, umaimaz123 commented on app/javascript/custom/select2.js
> +        }
whem I use "html" instead of "append" it does not allowing me to select multiple products even though i have added multiple: true. and in case of "replaceWith" it does not take parameters to pass to  controller. whereas "append" is working fine in both situations.

2022-02-11 05:57 UTC, merged